### ISSUE TITLE
batch mode on match_pairs.py?

### ISSUE THREAD

**Issue by jamesguoxin** [magicleap/SuperGluePretrainedNetwork#25]
I noticed when running match_pairs.py on match mode, it seemed to match ONE image pair at a time, I'm wondering is it possible to run a batch of image pairs at a time? This should accelerate the speed when using GPU?
batch pairs = [im00, im01, im02, ... , im0n] with [im10, im11, im12, ..., im1n]

**Comment by Skydes** [comment]
The SuperGlue model can already run on batches of image pairs but only if all pairs have the same number of keypoints. Similarly, SuperPoint can run on batched images, but can detect different number of keypoints for each image. As such, you need to keep a fixed number of keypoints (e.g. add dummy keypoints). The performance gains might not be large if your GPU is not so powerful, since SuperGlue can already fill up all CUDA kernels if the number of keypoints is large.

**Comment by jamesguoxin** [comment]
Thank you for the clarification! @Skydes

**Comment by ddetone** [comment]
Hello @jamesguoxin, please close this issue if you have no further problems :)
