### ISSUE TITLE
already matched superpoints gone after adding new superpoints into array

### ISSUE THREAD

**Issue by fatihmd** [magicleap/SuperGluePretrainedNetwork#40]
In my case I have 2 images x,y. In the first scenario I have extracted 30 superpoints from image x and extract 512 superpoints from image y. In or to make the size of the arrays same, I created zeros array with size 512. I fill the first 30 element of that zeros array with the superpoints that I extracted from the image x. After that I used superglue and it gave rational matches between those images.

In the second scenario, I have added same 30 superpoints to the zeros array and it becomes filled with 60 superpoints(duplicate same superpoint set that I extracted from image x) and rest is zero. When I tried to match this array with the superpoint array from image y, it gave zero match. But I have used the same superpoints just duplicated them in the array.

Could anyone help me to understand the rational between this behavior of the superglue, thanks in advance.

**Comment by Skydes** [comment]
SuperGlue can handle image pairs with different numbers of keypoints - you thus don't need to zero-pad or duplicate the keypoint tensor.

The absence of matches when keypoints are duplicated is due to the optimal matching layer: it enforces a one-to-one mapping, which is clearly violated when duplicating keypoints. As a consequence, one keypoint is matched to multiple others, its probability mass (which sums to 1) is equally distributed among them, and none of these matches passes the filtering threshold that binarizes the assignment matrix. This behavior is expected.
