### ISSUE TITLE
Details for training on Megadepth

### ISSUE THREAD

**Issue by wangchuting** [magicleap/SuperGluePretrainedNetwork#54]
Hi, thanks for the excellent work!

I'm trying to train SuperGlue on the Megadepth dataset and have some questions about the details of data preprocessing.
I saw the [discussion](https://github.com/magicleap/SuperGluePretrainedNetwork/issues/52#issuecomment-753514361) said that the random cropping is used for MegaDepth. 
1. Is the random cropping method similar to D2-Net (selected a random w*h crop centered around one correspondence)？
2. What is the size of cropping (w*h)?

This is my first time to train such a big work, so maybe I am confused about some basic details.
Looking forward to your reply :)

**Comment by Skydes** [comment]
Hi there,
These are good questions - we indeed ignored these details in the paper.

Random cropping is necessary only if you need to extract the features online during training and thus need to batch the images. This allows to use other sorts of data augmentation, such as in the homography experiments. In this case, we resized the images such that their shortest dimension is fixed (e.g. 720 pixels) and crop a random square of this size.

If features are computed offline and loaded during training, then you can simply randomly drop a subset so that each element in the batch has a fixed number of features. This also acts as some kind of data augmentation. Overall both strategies work well for MegaDepth and ScanNet.

**Comment by bbikdash** [comment]
Hello,
This may be a silly question but how does SuperGlue use the MegaDepth dataset for training? Does it only use the traditional images in the dataset or does SuperGlue use the depth maps for training as well?

**Comment by Zhongyuan-Li** [comment]
Hi,
About the training on MegaDepth, I have some other confuses. 
  1.  As the paper mentioned, when training on indoor/outdoor scenes, due to the depth map errors. the negative samples are more strict. like reprojection error 3 for matched points and 5 for unmatched points. So this would leave some points with reprojection error between 3 and 5. Those points did not have specific status when calculating losses . Should we kick these points out before the superglue network or keep them and ignore them while calculating losses?
  2. The origin resolution in MegaDepth is 1600 by default(the maximum length). Due to the depth map errors, is the threshold 3 of reprojecton error  too strict? Or the pictures were resized to a lower resolution while training?
  
Thanks! Looking forward the replies!

**Comment by wangchuting** [comment]
> Hi there,
> These are good questions - we indeed ignored these details in the paper.
> 
> Random cropping is necessary only if you need to extract the features online during training and thus need to batch the images. This allows to use other sorts of data augmentation, such as in the homography experiments. In this case, we resized the images such that their shortest dimension is fixed (e.g. 720 pixels) and crop a random square of this size.
> 
> If features are computed offline and loaded during training, then you can simply randomly drop a subset so that each element in the batch has a fixed number of features. This also acts as some kind of data augmentation. Overall both strategies work well for MegaDepth and ScanNet.

**Comment by Skydes** [comment]
@bbikdash We use the depth map to obtain a pixelwise mapping between image pairs. Please refer to the paper for more details.

@Zhongyuan-Li
1. These points are simply ignored when calculating the loss.
2. I think that the images were resized to a minimum size of 720 pixels during training. The thresholds of 3 and 5 pixels are for this size.

@wangchuting Please close this issue if your question is answered.

**Comment by wangchuting** [comment]
> Hello,
> This may be a silly question but how does SuperGlue use the MegaDepth dataset for training? Does it only use the traditional images in the dataset or does SuperGlue use the depth maps for training as well?

[There](https://github.com/magicleap/SuperGluePretrainedNetwork/issues/52#issuecomment-753514361) is how to generate the ground truth. Therefore, to generate GT needs images, depth maps and SfM models in MegaDepth, and you can reference [D2-Net](https://github.com/mihaidusmanu/d2-net).
