### ISSUE TITLE
Net archicture

### ISSUE THREAD

**Issue by zwyking** [magicleap/SuperGluePretrainedNetwork#71]
Hi, thanks for your excellent works. I want to ask a question, have you ever try to concatenate the keypoints and descriptors rather than adding directly? From mt view, i think the two domain features added directly is a little strange.

**Comment by Skydes** [comment]
We had indeed some earlier experiments comparing summing with concatenation. At that time, the results were similar but summing was more efficient and resulted in faster convergence, since the network behaves like NN matching at initialization. With the final architecture and longer training times, concatenation might be slightly more effective but I do not have numbers to back this.

**Comment by zwyking** [comment]
Ok,  thanks for your patient response!
